language: ruby
rvm:
- 2.3.3
services:
- postgresql
before_script:
- psql -U postgres -c 'create user defo;'
- psql -U postgres -c 'create database testcatalog_test with owner defo;'
- cp .env.yml.travis .env.test
- bundle exec rails db:migrate RAILS_ENV=test
script:
- bundle exec rspec
- bundle exec rspec spec/features/products_index_spec.rb
deploy:
  provider: heroku
  api_key:
    secure: U2bqdUY31ziG+ebW3dwWYxljqsdfqX9xz6k1XzQWCOGPYFL5wIB/jw5Gi4Q94c4MN+4FBf6AludYd05JVRnfepMzPt1dDTjJ3aV0+9la8U7nDbwwU7Nn4uN4Kj+mXr5KuFCGtHK0n7SXEXSA05P/5nszAXnF+3GntRzwUFIEPuZD6Wi6dNqwsKEHObcVJJTVhF52Zzbq0c/qXABh7EJpWveeJCrYxjwWFM0F1Yj7AAmK4W4AhLWPeBeH2b8y5KapLvtGDIDhDxyQ4LOSqFKzP6Y0qrfxXhQQZwg6XUqkPW7tSQCwCT4QzlG1RmeJqBJNVjT4hl6iijIdl3AeBaxfX0xztOUIlPOH2XrlUIV8QWqoDFxUhh5bFqiZkAmlaysrRL0NhLbolIi3Z+W79j+MYXJPba6r5f9rAwSjZXXvDQaxaTUvBO19S7WdPw0cJDpAkGYKrbxhT9AGFJDoJuNVgWK3yk14hzB7oPpJIBBfXnO51VHmmn/6PMk5rYnNK9V86ij1ejM07Q8FrM3s+PvjeJllcr+YJUCgJlwzGOrxAmFFKjc+pp5he2iK8zmQWgL2L4+W5Pove/qzy/9RcGOdpWKwMhUby8Zj7sGcnGmtS2G5dfUUbaKeKQuJZ9DaOJO5fY8iBn/uSa5x3C9UsYrZzBAzlm3Vsz3wVRSNoHFRy+s=
  app: sheltered-ridge-31406
  on:
    repo: AdaevK/test_catalog
  run:
  - rails db:migrate
